language: elixir
elixir: 1.7.3
otp_release: 21.0
sudo: false

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

cache:
  directories:
    - _build
    - deps

env:
  - MIX_ENV=test
  global:
  - PGPORT=5433

script:
  - mix ecto.create
  - mix test
